#!/bin/bash

en="/etc/nginx/sites-enabled/$1"

if [ -f "$en" ]
then
	echo "$1 site is enabled"
	rm /etc/nginx/sites-enabled/$1
	echo "you have to manually restart nginx"
else
	echo "$en not found. are you sure that $1 is what you want to disable ?"
fi
