#!/bin/bash

file="/etc/nginx/av/$1"

if [ -f "$file" ]
then
	echo "enabling $1 site"
	ln -s /etc/nginx/av/$1 /etc/nginx/en/$1
	echo "you have to manually restart nginx"
else
	echo "$file not found. are you sure that $1 is what you want to enable ?"
fi
