#!/bin/sh

backupdir=/var/backups

if [[ ! -e $backupdir ]]; then
    mkdir -p $backupdir
elif [[ ! -d $backupdir ]]; then
    echo "$backupdir already exists but is not a directory - nasol moment" 1>&2
fi

cd $backupdir || exit 0

for FILE in passwd group shadow gshadow; do
        test -f /etc/$FILE              || continue
        cmp -s $FILE.bak /etc/$FILE     && continue
        cp -p /etc/$FILE $FILE.bak && chmod 600 $FILE.bak
done
unset backupdir
exit
